# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  jobs:
  - job: macOS
    pool:
      name: BlueQuartz Self Hosted
      demands: agent.os -equals Windows_NT
    steps:
    - script: echo FROM Freaking Windows? Maybe!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
  - job: Windows
    pool:
      name: BlueQuartz Self Hosted
      demands: agent.os -equals Darwin
    steps:
    - script: echo Hello Mojave!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
